version: "3.7"

services:
  web:
    build: .
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4000:4000"
    networks:
          websec:
              ipv4_address: 10.10.10.15

  mongo:
    image: mongo:4.4
    user: mongodb
    expose:
      - 27017
    networks:
          websec:
              ipv4_address: 10.10.10.16
              
              
  apisix:
    container_name: "apisix"
    image: santosomar/api_gateway:latest
    restart: unless-stopped
    volumes:
      - /opt/api_gateway/config.yml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
    networks:
          websec:
              ipv4_address: 10.10.10.17
  etcd:
    container_name: "etcd"
    image: bitnami/etcd:3.4.15
    restart: unless-stopped
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
          websec:
              ipv4_address: 10.10.10.18


