version: "3"
services:
  vulnado:
    build: .
    ports:
      - 8080:8080
    links:
      - db
      - internal_site
    environment:
      - PGPASSWORD=vulnado
      - PGDATABASE=vulnado
      - PGHOST=db:5432
      - PGUSER=postgres
    depends_on:
      - "db"
    networks:
      - internal
      - websec:
            ipv4_address: 10.10.10.6

  client:
    build: client
    ports:
      - 1337:80
    networks:
      - internal
      - websec

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=vulnado
      - POSTGRES_DB=vulnado

  internal_site:
    build: internal_site
    networks:
      - internal
      - websec


networks:
  websec:
    external: true
  internal:
    external: false
